apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: hippo
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-gis:centos8-13.6-3.1-4.7.5
  postgresVersion: 13
  instances:
    - name: instance2
      replicas: 3
      resources:
        limits:
          #cpu: 8.0
          #memory: 12Gi
      dataVolumeClaimSpec:
        accessModes:
        - "ReadWriteOnce"
        resources:
          requests:
            storage: 10Gi
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:centos8-13.6-4.7.5
      pgbackrest:
        global:
          repo1-retention-full: "14"
          repo1-retention-full-type: time
      manual:
        repoName: repo1
        options:
         - --type=full
      repos:
      - name: repo1
        schedules:
          full: "0 1 * * *"
          incremental: "0 */4 * * *"
        volume:
          volumeClaimSpec:
            accessModes:
            - "ReadWriteOnce"
            resources:
              requests:
                storage: 20Gi
  monitoring:
    pgmonitor:
         exporter:
            image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres-exporter:centos8-4.7.5
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:centos8-13.6-4.7.5
      replicas: 2
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 1
            podAffinityTerm:
              topologyKey: kubernetes.io/hostname
              labelSelector:
                matchLabels:
                  postgres-operator.crunchydata.com/cluster: hippo-ha
                  postgres-operator.crunchydata.com/role: pgbouncer
  users:
    - name: ayman
      databases:
        - postgres
        - hippo
        - tarfdb
    - name: hippo
      databases:
        - postgres
      options: "CREATEDB"
    - name: postgres
    - name: con
      databases:
          - hippo
          - tarfdb
          - iot
